name: batch_rename
description: A CLI tool to help batch renaming files.
version: 1.0.1
# homepage: https://www.example.com
repository: https://github.com/POWRFULCOW89/batch-rename-dart

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
